image: registry.opensuse.org/home/okurz/container/ca/containers/tumbleweed:curl-jq-ssh-git

stages:
  - mirror

mirror-from-github:
    retry: 2
    stage: mirror
    rules:
          - if: $CI_PUSH_TOKEN
    script:
        - git config user.email "you@example.com"
        - git config user.name "Your Name"
        - "git remote add github https://github.com/os-autoinst/os-autoinst-needles-opensuse ||:"
        - git fetch github master:gmaster
        - git remote set-url origin ${CI_SERVER_PROTOCOL}://does_not_matter:${CI_PUSH_TOKEN}@${CI_SERVER_FQDN}/${CI_PROJECT_PATH}.git
        - git push -f origin gmaster:master
